### PR TITLE
#235 field value list with single value

### PR DESCRIPTION
**Pull request by t-h-e**

### CODE REVIEW

**Review by cmunozgomez — CHANGES_REQUESTED** [review]
Hi @t-h-e,

As the project is structured, we highly recommend that some changes be made to the pull request that you propose.

You propose to eliminate the main methods in charge of the sequences in RandomObject.java and for this purpose create a new class that will be the one that is instantiated with said methods and logic for the sequences. So far there is no problem, but for this purpose we consider that it is better that you do not instantiate this new class within RandomObject to access it and that you directly transfer the generateSeq and generateSequenceForFieldValueList methods to said class and it is in charge of all that logic related to as sequences, separating it from RandomObject. This of course will therefore affect SchemaProcessorLib.java, AvroGeneratorTool.java, StatelessGeneratorTool.java, among perhaps others.

Continuing with these changes that we propose, rename SequenceSupport to something more similar to the classes, for example, one proposal is RandomSequence.java. Within this class, subtract the class declared within SequenceType<T> from another route such as random/model and declare it as public, the reason is not to overcomplicate the code since we are also going to use this new RandomSequence.java class(the previous name proposal) in charge of the logic of all sequences, but this may change in the future. This way SequenceType<T> can be extended and reused.

I am not asking you for any more changes in principle, but keep in mind that we will surely make adjustments and changes to your changes according to the roadmap that we have set. For example, and to make you aware of it, in the sequences of decimal types (Decimal, Float...) we only treat the integer part of the decimal, but that will change according to the roadmap.

Thank you very much in advance and I am very sorry for the long explanation.

Cheers

**Comment by t-h-e** [comment]
Hi @cmunozgomez,

Thanks for the feedback. I hope the changes meet your requests.

**Review by cmunozgomez — APPROVED** [review]
hi @t-h-e 


Thank you very much for making the requested changes.

Once the rest of the reviewers give their approval and if you don't have to make any more changes to the code, the merge will proceed.

Cheers

**Review by Rivarsal — APPROVED** [review]

**Review by jmejutovazquez — APPROVED** [review]

**Comment by t-h-e** [comment]
Thanks for the approvals. The "Java CI with Maven (PR) / build (pull_request)" job seems not to work: `Error: The process '/usr/bin/git' failed with exit code 1`
Otherwise the PR could be merged

**Pull request merged**
