### PR TITLE
Record with default null value

### PR DESCRIPTION
**Pull request by Vichukano**
Hi!

If we have complex nested record type with default null value like:
{"name": "fix", "type": ["null", "type": {"type": "record", "name": "nestedRecord"}], "default": null}
that will fall with exception in method AvroSchemaProcessor.extractType, cause thing that is an array.

And it can't parse complex schema with nested records with similar names, which represents in fieldValue mapping
like fizzbuzz.fizz.fizzbuzz.
In this case "fizzbuzz.fizz.fizzbuzz".contains("fizz") will be always true for first part of field name.
To solve this problem i add some checking by regexp.

### CODE REVIEW

**Review by kszosze — APPROVED** [review]
Thank you for collaborate. Do you mind, just before merge, let the imports in the way it were before?
Thanks!!

**Comment by Vichukano** [comment]
Sorry, i restore imports.

**Comment by kszosze** [comment]
No problem Is ok, I´m gonna accept this changes. But I´m curious about the array failure you mention in the issue. What was about? Can you provide a avsc + jmx for testing it? 
tx!

**Comment by Vichukano** [comment]
Hola!
Sorry for long time answer.
Can't add jmx and avro schema in which i has a parsing problem, because of my work politics.
But i add sample of schema with same fields structure.
[TestAvro.avsc.txt](https://github.com/corunet/kloadgen/files/5683108/TestAvro.avsc.txt)

**Pull request merged**
