### PR TITLE
#313 solved serializers casting problems using SpecificDatumWriter

### PR DESCRIPTION
**Pull request by davidgarciago**
The casting problem of long_timestamp-millis gets solved when using the GenericDatumWriter. Despite the lack of documentation it seems that we should use SpecificDatumWriter only when needed.

### CODE REVIEW

**Review by RaulBejaranoSngular — APPROVED** [review]

**Review by pedror19 — DISMISSED** [review]

**Review by jemacineiras — CHANGES_REQUESTED** [review]
Pom version should be updated

**Comment by davidgarciago** [comment]
I have added a new docker file from the #303 issue branch. I think it can be usefull to test the plugin.

**Review by dianaGomezGar — DISMISSED** [review]

**Comment by davidgarciago** [comment]
All changes requested have been commited. Please @jemacineiras review them when you have time.

**Comment by davidgarciago** [comment]
I have added new tests for the serializers. I also removed the use of SpecificDatumWritter from both serializers affected by the issue because it was never used. The reason of this was that serializers data was always of type GenericRecord and not SpecificRecord.

**Review by pedror19 — APPROVED** [review]

**Review by jemacineiras — APPROVED** [review]

**Pull request merged**
